apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: autoscale-demo-sm
  namespace: monitoring
  labels:
    release: monitoring      # MUST MATCH PROMETHEUS OPERATOR
spec:
  selector:
    matchLabels:
      app: autoscale-demo
  namespaceSelector:
    matchNames:
      - project1-autoscale-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
