apiVersion: v1
kind: Service
metadata:
  name: autoscale-demo
  namespace: project1-autoscale-demo
  labels:
    app: autoscale-demo
spec:
  selector:
    app: autoscale-demo
  ports:
  - name: http
    port: 80 
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
