apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: autoscale-demo-vpa
  namespace: project1-autoscale-demo 
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoscale-demo
  updatePolicy:
    updateMode: "Auto"